using Test
using AtmosphericSlowManifold

include("test_wsindy_discovery.jl")
include("test_gspt_fold.jl")
include("test_scm_backends.jl")
include("test_observation_ingestion.jl")
include("test_spectral_transform.jl")
include("test_wsindy_engine.jl")
include("test_geometry_core.jl")
include("test_geometry_foundations.jl")
include("test_canards.jl")
include("test_discovery_ir.jl")
include("test_discovery_modules.jl")
include("test_synthetic_benchmarks.jl")
include("test_identifiability.jl")
include("test_loso_validation.jl")
include("test_discover_closure_pipeline.jl")
include("test_model_selection.jl")
include("test_calibration_interface.jl")
include("test_uncertainty_propagation.jl")
include("test_end_to_end_pipeline.jl")
include("test_latex_exporter.jl")
include("test_export_utilities.jl")
include("test_pde_closure_coupling.jl")
include("test_diagnostics.jl")
include("test_most_closure.jl")
include("test_surface_boundary.jl")
include("test_surface_forcing.jl")
