# src/Discovery/Discovery.jl
include("SymbolicExtraction.jl")
include("LibraryBuilder.jl")
include("ConstraintBuilder.jl")
include("TestFunctions.jl")
include("WeakForms.jl")
include("SparseRegression.jl")
include("WSINDyEngine.jl")
include("SymbolicVerification.jl")
include("LaTeXExporter.jl")
include("ModelSelection.jl")
